---
- name: Setup TFTPD (OpenBSD)
  include: openbsd.yml
  when: not skip_openbsd and ansible_distribution == "OpenBSD"

- name: Install Netboot files
  include: netboot-setup.yml

- name: Setup Syslinux
  include: netboot-syslinux.yml

- name: Setup OpenBSD pxeboot
  include: pxeboot-openbsd.yml

