---
- name: Setup TFTPD (OpenBSD)
  include_tasks: openbsd.yml
  when: not skip_openbsd and ansible_distribution == "OpenBSD"

- name: Install Netboot files
  include_tasks: netboot-setup.yml

- name: Setup Syslinux
  include_tasks: netboot-syslinux.yml

- name: Setup OpenBSD pxeboot
  include_tasks: pxeboot-openbsd.yml

