---
- name: Download tarballs
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ netboot_tarballs }}"

- name: Create destination folders
  file:
    dest: "{{ item.folder }}"
    state: directory
  with_items:
    - "{{ netboot_tarballs }}"

- name: Unpack tarballs
  shell: "tar -C {{ item.folder }} -xzf {{ item.dest }}"
  with_items:
    - "{{ netboot_tarballs }}"

