---
- name: Enable the DHCPD service
  shell: rcctl enable dhcpd

- name: Set DHCPD flags
  shell: rcctl set dhcpd flags {{ dhcp_interfaces }}

- name: Configure the DHCPD service
  template: src="{{ ansible_distribution }}-dhcpd.conf" dest=/etc/dhcpd.conf
  # loop: "{{ subnets }}"
  notify:
    - "restart {{ ansible_distribution }} dhcpd"

