---
- name: Copy over sysctl file
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    mode: 0640
    owner: root
    group: wheel

- name: Ensure that PF is enabled
  shell: pfctl -e
  ignore_errors: yes

- name: Copy over pf file
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
    mode: 0640
    owner: root
    group: wheel

- name: Check that PF rules are syntactically valid
  shell: pfctl -n -f /etc/pf.conf
  register: pf_rules_valid
  failed_when: not pf_rules_valid

- name: Load PF rules
  shell: pfctl -f /etc/pf.conf

