---
netboot_tarballs:
  - url: https://deb.debian.org/debian/dists/bookworm/main/installer-amd64/current/images/netboot/netboot.tar.gz
    dest: "{{ pxe.bootdir }}/debian12-amd64-netboot.tar.gz"
    mode: "0644"
    folder: "{{ pxe.bootdir }}/debian12"
  - url: https://deb.debian.org/debian/dists/bookworm/main/installer-i386/current/images/netboot/netboot.tar.gz
    dest: "{{ pxe.bootdir }}/debian12-i386-netboot.tar.gz"
    mode: "0644"
    folder: "{{ pxe.bootdir }}/debian12"

syslinux:
  url: https://mirrors.edge.kernel.org/pub/linux/utils/boot/syslinux
  version: "6.03"
  dest: "{{ pxe.bootdir }}"

pxe:
  bootdir: "/pxe"
  bootmenu:
    - menu_label: "debian-12-amd64"
      name: "Debian 12 AMD64"
      kernel: "debian12/debian-installer/amd64/linux"
      append: "initrd=debian12/debian-installer/amd64/initrd.gz"
    - menu_label: "debian-12-amd64-gnome-auto"
      name: "Debian 12 AMD64 Gnome Desktop"
      kernel: "debian12/debian-installer/amd64/linux"
      append: "initrd=debian12/debian-installer/amd64/initrd.gz auto=true priority=high netcfg/get_hostname?= netcfg/get_domain?={{ domain }} preseed/url=tftp://{{ tftpd_server }}/preseed-amd64-gnome.cfg vga=788 --- quiet"
    - menu_label: "debian-12-i386"
      name: "Debian 12 i386"
      kernel: "debian12/debian-installer/i386/linux"
      append: "initrd=debian12/debian-installer/i386/initrd.gz"
    - menu_label: "debian-12-i386-cinnamon-auto"
      name: "Debian 12 i386 Cinnamon Desktop"
      kernel: "debian12/debian-installer/i386/linux"
      append: "initrd=debian12/debian-installer/i386/initrd.gz auto=true priority=high netcfg/get_hostname?= netcfg/get_domain?={{ domain }} preseed/url=tftp://{{ tftpd_server }}/preseed-686-cinnamon.cfg vga=788 --- quiet"
    - menu_label: "openbsd"
      name: "OpenBSD 7.5"
      kernel: "syslinux-6.03/bios/com32/modules/pxechn.c32"
      append: "pxeboot"

  openbsd:
    base_url: "http://ftp.openbsd.org/pub/OpenBSD"
    versions:
      - "7.5"
    archs:
      - "amd64"
    files:
      - "pxeboot"
      - "bsd.rd"
  
  binaries:
    - src: "bios/core/pxelinux.0"
      dest: "pxelinux.0"
    - src: "bios/core/ldlinux.sys"
      dest: "ldlinux.sys"
    - src: "bios/com32/elflink/ldlinux/ldlinux.c32"
      dest: "ldlinux.c32"
    - src: "bios/com32/menu/menu.c32"
      dest: "menu.c32"
    - src: "bios/com32/menu/vesamenu.c32"
      dest: "vesamenu.c32"
    - src: "bios/com32/lib/libcom32.c32"
      dest: "libcom32.c32"
    - src: "bios/com32/libutil/libutil.c32"
      dest: "libutil.c32"

  preseed:
    arch:
      - "686"
      - "amd64"
    desktop:
      - "cinnamon"
      - "gnome"

