---
- name: Setup hosts
  become: yes
  hosts: all

  vars:
    skip_openbsd: False
    skip_freebsd: False
    skip_linux: False

  roles:
    - { role: add-user,         tags: [ 'users' ] }
    - { role: setup-interfaces, tags: [ 'interfaces', 'nics', 'nic' ] }
    - { role: setup-dhcpd,      tags: [ 'dhcpd' ], when: "install_dhcpd|bool" }
