---
- name: Setup hosts
  become: yes
  hosts: all
  
  vars_files:
    - ~/credentials/become_passwords.yml

  roles:
    - { role: add-user,         tags: [ 'users' ] }
    - { role: setup-interfaces, tags: [ 'interfaces', 'nics', 'nic' ] }
