---
# Setup OpenBSD hosts for use with ansible. Assumes the following:
# - OpenBSD is installed on the target box
# - an initial user is provisioned with passwordless ssh

- hosts: openbsd
  gather_facts: false
  become: yes

  tasks:
  - name: Install Python3
    raw: pkg_add python3

